#!/usr/bin/env ruby
# frozen_string_literal: true

require "hot_cell/server"

development = ARGV.delete("--development") ? true : false
abort "usage: hotcell [--development]" unless ARGV.empty?

HotCell.load!

HotCell::Supervisor
  .new(directory: ENV.fetch("HOTCELL_DIR", "/run/hotcell/cell"), workspace: ENV["HOTCELL_WORKSPACE"],
       development: development)
  .boot
  .run
