#!/usr/bin/env ruby
# frozen_string_literal: true

require "hot_cell/server"

HotCell.load!

HotCell::Supervisor
  .new(directory: ENV.fetch("HOTCELL_DIR", "/run/hotcell/cell"), workspace: ENV["HOTCELL_WORKSPACE"])
  .boot
  .run
