# frozen_string_literal: true

require "rake/testtask"
require "rbconfig"
require_relative "../test/support/mutations"

Rake::TestTask.new(:test) do |task|
  task.libs << "test"
  task.test_files = FileList["test/**/*_test.rb"]
  task.warning = true
end

MUTATIONS = {}.freeze

desc "Break each control in turn and confirm the suite notices"
task :mutations do
  survivors = MUTATIONS.reject do |mutation, suite|
    output = `#{RbConfig.ruby} -Ilib -Itest -rmutations/#{mutation} test/#{suite} 2>&1`
    caught, summary = Mutations.caught?(output)
    puts format("  %-30s %-26s %-9s %s", mutation, suite, caught ? "caught" : "SURVIVED", summary)
    caught
  end

  abort "the suite does not hold: #{survivors.keys.join(", ")}" if survivors.any?
end

task default: :test
