# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

require "minitest/autorun"
require "tempfile"
require "tmpdir"
require "socket"
require "json"
require "shellwords"

# Nothing here loads libvips into the test process, and that is not incidental. The suite boots real cells by
# forking, and libvips' thread pool does not survive a fork — one evaluation in this process would make every
# forked worker deadlock. So the operations load inside the cell, the fixtures are generated by CLI tools rather
# than in Ruby, and fork_safety_test.rb is what holds the line.
require "hot_cell/test_cell"

require_relative "support/cell"

class ActiveStorageHotCellTest < Minitest::Test
  FIXTURES = File.expand_path("fixtures", __dir__)

  private
    def fixture(name)
      File.join FIXTURES, name
    end

    # The extension matters to the tools that read the result back, not to the operation: it chooses its saver
    # from the requested format and hands back a file whose name it never sees.
    def with_output(extension = ".bin")
      Tempfile.create([ "out", extension ], binmode: true) { |file| yield file.path }
    end

    def assert_ok(response)
      assert response, "expected a response and got none"
      assert_predicate response, :ok?, "expected ok and got #{response.failure&.to_s.inspect}"
      response
    end

    def assert_failed(code, response, cause: nil)
      assert response, "expected a response and got none"
      refute response.ok?, "expected #{code} and the response was ok: #{response.result.inspect}"
      assert_equal code, response.failure.code
      assert_equal cause, response.failure.cause if cause

      response.failure
    end

    # What ImageMagick sees, so a claim about the produced bytes does not come from the library that wrote them.
    #
    # One line per frame, and a format string is repeated once per frame too — which is how the first version of
    # this read a frame count out of the wrong token and blamed the operation for it.
    def identify(path)
      lines = `magick identify -format '%w %h %m\n' #{path.shellescape} 2>/dev/null`.lines
      skip "ImageMagick is not installed" if lines.empty?

      width, height, format = lines.first.split
      { width: Integer(width), height: Integer(height), format: format, frames: lines.size }
    end
end
